### ISSUE TITLE
Perl error on building.

### ISSUE THREAD

**Issue by aquiles2k** [movableink/webkit#29]
When building with msvc i get the following error:

```
Erstellen gestartet...
1>------ Erstellen gestartet: Projekt: Bytecodes, Konfiguration: Release x64 ------
2>------ Erstellen gestartet: Projekt: JavaScriptCore_CopyHeaders, Konfiguration: Release x64 ------
3>------ Erstellen gestartet: Projekt: WTF_CopyHeaders, Konfiguration: Release x64 ------
4>------ Erstellen gestartet: Projekt: JSCBuiltins, Konfiguration: Release x64 ------
5>------ Erstellen gestartet: Projekt: JavaScriptCoreSharedScripts, Konfiguration: Release x64 ------
6>------ Erstellen gestartet: Projekt: JavaScriptCore (JavaScriptCore\JavaScriptCore), Konfiguration: Release x64 ------
6>Generating ../../JavaScriptCore/DerivedSources/inspector/InspectorBackendDispatchers.cpp, ../../JavaScriptCore/DerivedSources/inspector/InspectorBackendDispatchers.h, ../../JavaScriptCore/DerivedSources/inspector/InspectorFrontendDispatchers.cpp, ../../JavaScriptCore/DerivedSources/inspector/InspectorFrontendDispatchers.h, ../../JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.cpp, ../../JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h, ../../JavaScriptCore/DerivedSources/inspector/InspectorBackendCommands.js
6>Traceback (most recent call last):
6>  File "D:\Dev\Sources\qtwebkit-2022-09-07-src\Source\JavaScriptCore\inspector\scripts\generate-inspector-protocol-bindings.py", line 306, in <module>
6>    generate_from_specification(**options)
6>  File "D:\Dev\Sources\qtwebkit-2022-09-07-src\Source\JavaScriptCore\inspector\scripts\generate-inspector-protocol-bindings.py", line 233, in generate_from_specification
6>    subprocess.check_call(["perl", os.path.join(os.path.dirname(__file__), "codegen", "preprocess.pl"), "--input", temporary_input_filepath, "--defines", protocol.condition_flags, "--output", temporary_output_filepath])
6>  File "C:\Python312\Lib\subprocess.py", line 408, in check_call
6>    retcode = call(*popenargs, **kwargs)
6>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
6>  File "C:\Python312\Lib\subprocess.py", line 389, in call
6>    with Popen(*popenargs, **kwargs) as p:
6>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
6>  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
6>    self._execute_child(args, executable, preexec_fn, close_fds,
6>  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
6>    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
6>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6>FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

So the python script tries to call a perl script, which errors out because of some file not found error. I checked that Perl is in Path and verified that in the source folder "codegen" a perl-script named preprocess.pl is found.

I have no clue what file is not found.

**Comment by aquiles2k** [comment]
I set visual studios verbosity up to get the exact call which, in my personal case, was:
```
C:\Python312\python.exe D:/Dev/Sources/qtwebkit-2022-09-07-src/Source/JavaScriptCore/inspector/scripts/generate-inspector-protocol-bindings.py --outputDir D:/Dev/Builds/qtwebkitcmake/JavaScriptCore/DerivedSources/inspector --framework JavaScriptCore D:/Dev/Builds/qtwebkitcmake/JavaScriptCore/DerivedSources/CombinedDomains.json
```
Executing this directly in the windows terminal succeded and generated some files in JavaScriptCore\DerivedSources\inspector

After that i restarted the build and it continued happily.

I'm leaving this open since i still dont know how to achieve this without manual interference.
